### ISSUE TITLE
Чеклист к РК №2

### ISSUE THREAD

**Issue by reo7sp** [frontend-park-mail-ru/2018_1_shark_team#15]
https://park.mail.ru/blog/topic/view/11330/

- [x] Сделаны все дз
    - [x] ДЗ №5
    - [x] ДЗ №6
    - [x] ДЗ №7
    - [x] ДЗ №8
- [x] У вас есть синглплеер и в него можно поиграть!
- [x] Ваш код написан с использованием синтаксиса ES6-модулей, также у вас наcтроен транспайлинг кода с помощью babel (или с помощью TypeScript)
- [x] В ваших проектах есть правильно работающий роутинг, работают переходы по страницам и меняется адрес в адресной строке браузера
- [x] Вы используете БЭМ или другую методологию написания CSS
- [x] Ваше приложение может запускаться и работать offline (т.е. без соединения с интернетом). В вашу игру можно поиграть offline

**Comment by maxim218** [comment]
Несколько пунктов уже готово.
