### ISSUE TITLE
Доработки к РК-2

### ISSUE THREAD

**Issue by ostapenko-me** [frontend-park-mail-ru/2018_1_shark_team#17]
# Косяки

- [ ] Передайте на REST *-2 балла*
- [x] Принудительный редирект на `https:`
- [x] Добиться работоспособности приложения на `https:`
- [x] Должна быть возможность игры незарегистрированным пользователем
- [x] Разноообразить игровую механику *-10 баллов*. Например:
  - открывать приложение fullscreen
  - добавить музыку
  - добавить анимации движения вверх/вниз
  - добавить жизни, возможность стрелять
- [ ] Переработать логику работы чатика — отправлять на клиент сообщение только с уведомлением о новом письме. Не грузить канал связи пересылкой туда/сюда одних и тех же сообщений *-5 баллов*
- [x] ВСЁ приложение должно быть доступно offline *-2 баллов*
- [x] Доработать стиль js-кода. Избавиться от всех мест, где происходят не нужные сравнения, типа `if (login.length === 0) {` -> `if (!login.length) {` и ещё кое-что
- [x] Очень много мест с копипастой кода. Выносить общие части в циклы *-2 баллов*
- [x] При регистрации нас сразу должно авторизовывать. Не нужно заставлять пользователя дважды вводить логин/пароль *-1 баллов*
- [x] Запрограммировать модуль, который будет показывать всплывающие окна. И использовать его для показа пользователю ошибок *-2 баллов*

**Comment by maxim218** [comment]
Исправил часть

**Comment by maxim218** [comment]
Вот ссылка http://client-funny-race-game.herokuapp.com/sign-up

**Comment by maxim218** [comment]
Добавил игровую механику (стрельба, анимация, полноэкранный режим). Музыки пока нет.

**Comment by maxim218** [comment]
Добавил звук в игре: есть музыка на заднем фоне, звук стрельбы, звук взрыва ракеты.
