### ISSUE TITLE
Чеклист к РК №3

### ISSUE THREAD

**Issue by reo7sp** [frontend-park-mail-ru/2018_1_shark_team#18]
https://park.mail.ru/blog/topic/view/11485/

Чеклист:
- [x] Вы исправили большинство недоработок сингл-версии вашей игры и начали разрабатывать мультиплеер по сети
- [x] В вашем приложении присутствует адаптивная вёрстка. Оно хорошо выглядит и работает на мобильных устройствах
- [x] Адаптируйте ваши приложения для работы на мобильных устройствах и планшетах. Приложение должно адекватно отображаться и работать на смартфонах и планшетах. Для отладки вёрстки можно использовать обычный браузер: в хроме есть режим эмуляции мобильных устройств. Будет большим плюсом, если в вашу игру можно будет поиграть и на устройствах с сенсорным экраном, современные смартфоны и планшеты по техническим характеристикам мало уступают компьютерам, а возможности браузеров везде плюс-минус одинаковые. Если адаптировать игру под мобилки ну никак не получается, то, как минимум, покажите пользователю уведомление об этом. У пользователя не должно возникать шока от того, что он откроет ваше приложение на смартфоне :D
- [x] В этом модуле очень много было сказано про CSS, постарайтесь причесать ваше приложение, чтобы оно выглядело приятно и красиво. Тем более, что это не так и сложно..
Внедрите в ваши проекты инструменты для продвинутой работы с CSS: пре- и постпроцессоры, инструменты для сборки кода, перепишите ваши стили на SCSS (или любой другой синтаксис), избавьтесь от лишних префиксов, доверьте расстановку префиксов специальным плагинам. По желанию, подумайте, где можно использовать современные возможности CSS, такие как анимации, CSS-переменные и другие. Как всегда, приветствуются продуктовые решения! ;)

**Comment by maxim218** [comment]
Сделано =)
