### ISSUE TITLE
Доработки к РК-3

### ISSUE THREAD

**Issue by ostapenko-me** [frontend-park-mail-ru/2018_1_shark_team#20]
# Что нужно исправить:

- [x] фильтр по картинкам в инпуте выбора аватара
- [x] сайт слишком тяжёлый, оптимизируйте. два мегабайта это дохрена
- [ ] будучи авторизованным, нас не должно пускать на /signup
- [ ] доработайте мобильную версию, в текущем варианте этого не достаточно для получения максимального балла
- [ ] + необходимо реализовать мобильную версию мультиплеера
- [ ] используйте вложенность в scss
- [x] нельзя использовать вложенные селекторы `.a .b .c`
- [x] настройте линтинг стилей
- [x] переделайте меню с кнопок на ссылки, чтобы не нужно было на каждую кнопку навешивать свой обработчик.
- [x] переделайте isStringNormal.js на регулярки
- [x] добавьте прелоадер на экран загрузки игры с отображением процентов загрузки приложения (грузить всю статику аяксом и считать, сколько мегабайт осталось и сколько всего)
- [x] такой же прелоадер добавить и перед запуском самой игры
- [ ] разбить код вашего приложения на два бандла (с помощью webpack), один с приложением, второй с игрой и загружать бандл с игрой ТОЛЬКО когда мы заходим в саму игру
- [x] добавьте кеширование preflight-запроса
- [x] зачем запрашивать лидеров и аватарку при заходе на страницу about?

## чёт я проверил, и стало только хуже...
- [x] как управлять игроком с мобильного устройства?
- [x] при некоторых переходах между страницами происходит полная перезагрузка страницы.... у вас где-то есть `location = '...'`?
- [ ] какие-то постоянные дёрганья вёрстки... бесит
- [ ] писать везде `@extend .menu-button;` - сомнительно....
- [ ] зачем запрашивать loginycookies при переходах между страницами?
- [ ] в формах не работает сабмит по энтеру

**Comment by maxim218** [comment]
фильтр по картинкам в инпуте выбора аватара OK

**Comment by maxim218** [comment]
будучи авторизованным, нас не должно пускать на /signup и /login ОК

**Comment by maxim218** [comment]
зачем запрашивать лидеров и аватарку при заходе на страницу about, oneplayer, multiplayer, mainmenu и др OK

**Comment by ostapenko-me** [comment]
Чувак, не отмечайте чекбоксы, это — работа преподавателя, который прнмает РК.

**Comment by ostapenko-me** [comment]
Многое поправили, но всё равно очень много критических замечаний...

**Comment by reo7sp** [comment]
не зареференсилось ещё: #30
