### ISSUE TITLE
Чеклист к РК1

### ISSUE THREAD

**Issue by reo7sp** [frontend-park-mail-ru/2018_1_shark_team#5]
https://park.mail.ru/blog/topic/view/11068/

- [x] Ваше приложение задеплоено на heroku
- [x] Полностью выполнена интеграция с бекендом. В приложении присутствует кросс-доменное взаимодействие и правильно настроен CORS
- [x] Страницы приложения переключаются без перезагрузки сайта (то есть ваше приложение — это SPA)
- [x] Используется модульный и компонентный подход, используются шаблонизаторы
- [x] У вас работает регистрация и авторизация пользователей (с использованием cookies). Сессия пользователя сохраняется даже при перезагрузке браузера (вас не разлогинивает при закрытии вкладки)
- [x] В вашем приложении есть таблица лидеров. Данные в таблицу загружаются с сервара (хардкод запрещён). В таблице обязательно должна присутствовать пагинация. Запросы за списком пользователей тоже необходимо отправлять с пагинацией (грузить список всех пользователей сразу нельзя, нужно загружать их по частям)
- [x] В вашем приложении есть страничка с профилем текущего пользователя, должна присутствовать возможность загрузки пользовательских аватарок, возможность изменения настроек пользователя
- [x] Во всех формах присутствует валидация данных (для валидации используется js, валидация с помощью атрибутов форм запрещена). Любой невалидный ввод должен обозначаться сообщением об ошибке
- [x] Есть линтер, который не ругается на ваш код
- [x] API вашего приложения правильно составлено и задокументировано
- [x] В модулях вашего приложения также присутствует JSDoc-документация

> Для допуска к РК необходимо обязательно получить аппрув от ментора. Напоминаю, что для этого необходимо отправить ментору мерж-реквест с результатами вашей работы. Сделать это необходимо не позднее, чем за сутки до рубежного контроля. Команды, которые отправят мерж-реквест позже — допущены к РК не будут.

**Comment by maxim218** [comment]
Всё сделано =)
